version: '3.8'

# This override file should be used when running automated tests so
# that test output is saved to the host

services:
  ffc-sfd-experiment-ui:
    build:
      target: development
    image: ffc-sfd-experiment-ui-development
    environment:
      NODE_ENV: test
      GOOGLE_TAG_MANAGER_KEY: 'GT-MJPRKW7'
      SESSION_CACHE_TTL: 1200000
    container_name: ffc-sfd-experiment-ui-test
    command: npm run test
    volumes:
      - ./test-output/:/home/node/test-output/