{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfd-experiment-ui.config-map") -}}
{{- define "ffc-sfd-experiment-ui.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
{{- end -}}
