{{- include "ffc-helm-library.azure-ingress" (list . "ffc-sfd-experiment-ui.ingress") -}}
  {{- define "ffc-sfd-experiment-ui.ingress" -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.ingress.class }}
  rules:
    - host: {{ .Values.ingress.server }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.endpoint }}
                port:
                  number: 80
{{- end -}}
